kind: Secret
apiVersion: v1
metadata:
  name: regcred
  namespace: default #Give the Namespace where you want to create the secret
  uid: 99ccaca6-065b-461c-a2c9-40662df6662c
  managedFields:
    - manager: kubectl-create
      operation: Update
      apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:data:
          .: {}
          f:.dockerconfigjson: {}
        f:type: {}
data:
  .dockerconfigjson: >-
    ewoJImF1dGhzIjogewoJCSJoYXJib3Iuc3RqLnNhdmlvci5pbjo5NDQzIjogewoJCQkiYXV0aCI6ICJZV1J0YVc0NlNHRnlZbTl5TVRJek5EVT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson